BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "power-gateway"
BBFILE_PATTERN_power-gateway = "^${LAYERDIR}/"
BBFILE_PRIORITY_power-gateway = "8"

LAYERSERIES_COMPAT_power-gateway = "scarthgap styhead walnascar"
LAYERDEPENDS_power-gateway = "core openembedded-layer"
