#!/bin/sh

set -eu

: "${SDK_INSTALL_PATH:?Set SDK_INSTALL_PATH to MCU+ SDK 12.00.00.27}"

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
firmware_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
example="$SDK_INSTALL_PATH/examples/drivers/ipc/ipc_rpmsg_echo_linux"
common_source="$example/ipc_rpmsg_echo_linux.c"
staged="$example/power-alarm-src"

if [ ! -f "$common_source" ]; then
    echo "TI reference source not found: $common_source" >&2
    exit 1
fi

mkdir -p "$staged"
cp "$firmware_dir"/src/*.c "$staged"/
cp "$firmware_dir"/include/*.h "$staged"/

if [ ! -f "$common_source.ti-reference" ]; then
    cp "$common_source" "$common_source.ti-reference"
fi

cat > "$common_source" <<'EOF'
/*
 * Generated by m4-firmware/scripts/stage-ti-project.sh.
 * The TI reference is retained as ipc_rpmsg_echo_linux.c.ti-reference.
 */
#include "power-alarm-src/sysconfig_glue.c"
#include "power-alarm-src/board_ti.c"
#include "power-alarm-src/ipc_ti.c"
#include "power-alarm-src/main.c"
EOF

cat > "$staged/sysconfig_glue.c" <<'EOF'
#include <stdint.h>
#include "ti_drivers_config.h"

uint32_t gPowerAlarmGpioBaseAddr = CONFIG_GPIO0_BASE_ADDR;
uint32_t gPowerAlarmGpioPinNum = CONFIG_GPIO0_PIN;
uint32_t gPowerAlarmGpioBankIntrNum = CONFIG_GPIO0_INTR;
EOF

echo "Staged power-alarm sources in: $staged"
echo "Open the am62x-sk/m4fss0-0_freertos/ti-arm-clang SysConfig project."
echo "Configure CONFIG_GPIO0 exactly as documented, then run build-ti-project.sh."

